apiVersion: apps/v1
kind: Deployment
metadata:
  name: enjoy-front-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enjoy-front
  template:
    metadata:
      name: enjoy-front-pod
      labels:
        app: enjoy-front
    spec:
      containers:
        - name: enjoy-front-container
          image: 868422696413.dkr.ecr.ap-northeast-2.amazonaws.com/test:20250918-064554
          ports:
            - containerPort: 80
              #          volumeMounts:
              #            - name: nginx-config
              #              mountPath: /etc/nginx/conf.d
              #              readOnly: true
              #      volumes:
              #        - name: nginx-config
              #          configMap:
              #            name: nginx-config
